Add --disable-ntp parameter
hyle-team/zano pull request #317
Opened 2021-12-30 13:26 UTC by Derloda

2021-12-30 13:31 UTC, cryptozoidberg approved these changes

2021-12-30 21:58 UTC, sowle requested changes

2021-12-30 21:58 UTC, sowle commented on src/currency_protocol/currency_protocol_handler.inl
> +        return false;
```suggestion
      {
        LOG_PRINT_RED("TIME: network time difference is " << m_last_median2local_time_difference << " (max is " << TIME_SYNC_DELTA_TO_LOCAL_MAX_DIFFERENCE << ") while NTP is disabled", LOG_LEVEL_0);
        return false;
      }
```

I'd like to make it a bit more verbose. Feel free to change/rephrase the log message.

2022-01-04 05:12 UTC, sowle approved these changes

2022-01-04 05:13 UTC, sowle commented
Thank you!

2022-01-04 05:14 UTC, merged